// Static data for Kerala Tours Travel Application

import { Package, Vehicle, Service, Category, Review, ContactInfo } from '@/types';

export const companyInfo = {
    name: 'Golden Globe Tour Taxi Service',
    tagline: 'Best Travel Agency',
    slogan: 'From where you are to where you want me to be',
    description: 'We offer best cab services at affordable price. We offer city tours, airport taxi service, round trip cabs, self drive cars etc... more details get in touch with us or book your cab now.',
    locations: ['Golden Globe', 'Taxi Services', 'Pattambi', 'Palakkad'],
};

export const contactInfo: ContactInfo = {
    phone: '+91 9061883919',
    whatsapp: '919061883919',
    email: 'mdraffi114@gmail.com',
    owner: 'Muhammed Raffi R',
    address: 'Pallath house, Maruthur post, Pattambi, Palakkad district - 679306',
    locationDescription: 'Infront of Sevana Hospital, near Pattambi',
    googleMapsUrl: 'https://maps.app.goo.gl/nC2GSje1pVNpuHrDA',
};

export const packages: Package[] = [
    // KERALA PACKAGES
    {
        id: 'kerala-1',
        name: 'Kerala Backwaters Houseboat',
        destination: 'Alleppey',
        duration: '3 Days / 2 Nights',
        price: 12999,
        originalPrice: 15999,
        image: '/images/destination_alleppey.png',
        description: 'Cruise through the serene backwaters on a traditional houseboat. Experience authentic Kerala cuisine and village life.',
        highlights: ['Houseboat stay', 'Village visits', 'Kerala cuisine', 'Sunset views'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'kerala-2',
        name: 'Munnar Tea Garden Escape',
        destination: 'Munnar',
        duration: '3 Days / 2 Nights',
        price: 8999,
        originalPrice: 10999,
        image: '/images/destination_munnar.png',
        description: 'Escape to the cool hills of Munnar with lush tea gardens and misty mountains.',
        highlights: ['Tea gardens', 'Mattupetty Dam', 'Echo Point', 'Flower gardens'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'kerala-3',
        name: 'Wayanad Wildlife Adventure',
        destination: 'Wayanad',
        duration: '3 Days / 2 Nights',
        price: 11999,
        originalPrice: 14999,
        image: '/images/destination_wayanad.png',
        description: 'Explore the wildlife sanctuaries and natural beauty of Wayanad.',
        highlights: ['Wildlife safari', 'Edakkal Caves', 'Bamboo forest', 'Spice gardens'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'kerala-4',
        name: 'Thekkady Periyar Safari',
        destination: 'Thekkady',
        duration: '2 Days / 1 Night',
        price: 7999,
        originalPrice: 9999,
        image: '/images/destination_thekkady.png',
        description: 'Experience the famous Periyar Tiger Reserve with boat safari and spice plantation visits.',
        highlights: ['Tiger Reserve', 'Boat safari', 'Spice garden', 'Elephant ride'],
        category: 'kerala',
    },
    {
        id: 'kerala-5',
        name: 'Kovalam Beach Holiday',
        destination: 'Kovalam',
        duration: '3 Days / 2 Nights',
        price: 9999,
        originalPrice: 12999,
        image: '/images/destination_kovalam.png',
        description: 'Relax at the famous lighthouse beach and enjoy Ayurvedic treatments.',
        highlights: ['Lighthouse Beach', 'Ayurveda spa', 'Seafood', 'Water sports'],
        category: 'kerala',
    },
    {
        id: 'kerala-6',
        name: 'Kochi Heritage Walk',
        destination: 'Kochi',
        duration: '2 Days / 1 Night',
        price: 5999,
        originalPrice: 7999,
        image: '/images/destination_kochi.png',
        description: 'Explore the historic Fort Kochi with Chinese fishing nets and colonial architecture.',
        highlights: ['Fort Kochi', 'Chinese nets', 'Jewish Synagogue', 'Spice markets'],
        category: 'kerala',
    },
    {
        id: 'kerala-7',
        name: 'Bekal Fort & Beach',
        destination: 'Bekal',
        duration: '2 Days / 1 Night',
        price: 5999,
        originalPrice: 7999,
        image: '/images/hero_backwaters.png',
        description: 'Visit the historic Bekal Fort and enjoy pristine beaches.',
        highlights: ['Bekal Fort', 'Beach resort', 'Backwaters', 'Kerala cuisine'],
        category: 'kerala',
    },
    {
        id: 'kerala-8',
        name: 'Athirapally Falls Trip',
        destination: 'Athirapally',
        duration: '1 Day',
        price: 2999,
        originalPrice: 3999,
        image: '/images/destination_wayanad.png',
        description: 'Visit the majestic Athirapally waterfalls - the Niagara of India.',
        highlights: ['Waterfalls', 'Vazhachal Falls', 'Nature walk', 'Photography'],
        category: 'kerala',
    },
    {
        id: 'kerala-9',
        name: 'Kumarakom Bird Sanctuary',
        destination: 'Kumarakom',
        duration: '2 Days / 1 Night',
        price: 6999,
        originalPrice: 8999,
        image: '/images/destination_alleppey.png',
        description: 'Explore the famous bird sanctuary and enjoy houseboat experiences.',
        highlights: ['Bird watching', 'Houseboat', 'Fishing', 'Village life'],
        category: 'kerala',
    },
    {
        id: 'kerala-10',
        name: 'Vagamon Hills Retreat',
        destination: 'Vagamon',
        duration: '2 Days / 1 Night',
        price: 5499,
        originalPrice: 6999,
        image: '/images/destination_munnar.png',
        description: 'Experience the serene meadows and pine forests of Vagamon.',
        highlights: ['Pine forests', 'Paragliding', 'Tea estates', 'Trekking'],
        category: 'kerala',
    },
    // GOA PACKAGE
    {
        id: 'goa-1',
        name: 'Goa Beach Paradise',
        destination: 'Goa',
        duration: '4 Days / 3 Nights',
        price: 14999,
        originalPrice: 18999,
        image: '/images/destination_kovalam.png',
        description: 'Experience the vibrant beaches, nightlife, and Portuguese heritage of Goa.',
        highlights: ['Beach hopping', 'Water sports', 'Night markets', 'Church visits'],
        category: 'domestic',
        featured: true,
    },
    {
        id: 'goa-2',
        name: 'North Goa Adventure',
        destination: 'Goa',
        duration: '3 Days / 2 Nights',
        price: 11999,
        originalPrice: 14999,
        image: '/images/destination_kovalam.png',
        description: 'Explore the famous beaches and nightlife of North Goa.',
        highlights: ['Baga Beach', 'Calangute', 'Anjuna Market', 'Cruise'],
        category: 'domestic',
    },
    // OUTSIDE KERALA PACKAGES
    {
        id: 'mysore-1',
        name: 'Mysore Royal Heritage',
        destination: 'Mysore',
        duration: '3 Days / 2 Nights',
        price: 9999,
        originalPrice: 12999,
        image: '/images/destination_kochi.png',
        description: 'Discover the royal heritage and magnificent palaces of Mysore.',
        highlights: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens', 'Zoo'],
        category: 'outside-kerala',
        featured: true,
    },
    {
        id: 'ooty-1',
        name: 'Ooty Queen of Hills',
        destination: 'Ooty',
        duration: '4 Days / 3 Nights',
        price: 13999,
        originalPrice: 16999,
        image: '/images/cta_adventure.png',
        description: 'Visit the Queen of Hill Stations with toy train and botanical gardens.',
        highlights: ['Toy train ride', 'Botanical Garden', 'Ooty Lake', 'Tea factory'],
        category: 'outside-kerala',
    },
    {
        id: 'kodaikanal-1',
        name: 'Kodaikanal Princess of Hills',
        destination: 'Kodaikanal',
        duration: '3 Days / 2 Nights',
        price: 10999,
        originalPrice: 13999,
        image: '/images/destination_munnar.png',
        description: 'Explore the Princess of Hill Stations with its star-shaped lake.',
        highlights: ['Kodai Lake', 'Coakers Walk', 'Pillar Rocks', 'Pine Forest'],
        category: 'outside-kerala',
    },
    {
        id: 'bangalore-1',
        name: 'Bangalore Tech City Tour',
        destination: 'Bangalore',
        duration: '2 Days / 1 Night',
        price: 7999,
        originalPrice: 9999,
        image: '/images/service_city_tour.png',
        description: 'Explore the Silicon Valley of India with gardens and modern attractions.',
        highlights: ['Lalbagh Garden', 'Cubbon Park', 'Wonderla', 'Shopping'],
        category: 'outside-kerala',
    },
    {
        id: 'coorg-1',
        name: 'Coorg Coffee Estate',
        destination: 'Coorg',
        duration: '3 Days / 2 Nights',
        price: 12999,
        originalPrice: 15999,
        image: '/images/destination_wayanad.png',
        description: 'The Scotland of India with coffee plantations and waterfalls.',
        highlights: ['Coffee estates', 'Abbey Falls', 'Dubare Camp', 'Tibetan Camp'],
        category: 'outside-kerala',
        featured: true,
    },
    {
        id: 'rameshwaram-1',
        name: 'Rameshwaram Pilgrimage',
        destination: 'Rameshwaram',
        duration: '3 Days / 2 Nights',
        price: 8999,
        originalPrice: 10999,
        image: '/images/destination_kochi.png',
        description: 'Visit one of the holiest Hindu temples on the island.',
        highlights: ['Temple visit', 'Pamban Bridge', 'Dhanushkodi', 'Beach'],
        category: 'outside-kerala',
    },
    {
        id: 'madurai-1',
        name: 'Madurai Temple Tour',
        destination: 'Madurai',
        duration: '2 Days / 1 Night',
        price: 6999,
        originalPrice: 8999,
        image: '/images/destination_kochi.png',
        description: 'Visit the magnificent Meenakshi Temple and explore ancient Madurai.',
        highlights: ['Meenakshi Temple', 'Thirumalai Palace', 'Gandhi Museum', 'Local food'],
        category: 'outside-kerala',
    },
    {
        id: 'pondicherry-1',
        name: 'Pondicherry French Colony',
        destination: 'Pondicherry',
        duration: '3 Days / 2 Nights',
        price: 9999,
        originalPrice: 11999,
        image: '/images/destination_kovalam.png',
        description: 'Experience the French colonial charm and beautiful beaches.',
        highlights: ['French Colony', 'Auroville', 'Paradise Beach', 'Cafes'],
        category: 'outside-kerala',
    },
    // DOMESTIC TOUR PACKAGES
    {
        id: 'kashmir-1',
        name: 'Kashmir Paradise',
        destination: 'Kashmir',
        duration: '6 Days / 5 Nights',
        price: 29999,
        originalPrice: 35999,
        image: '/images/destination_munnar.png',
        description: 'Experience Heaven on Earth with Dal Lake and Gulmarg.',
        highlights: ['Dal Lake', 'Gulmarg', 'Shikara ride', 'Pahalgam'],
        category: 'domestic',
    },
    {
        id: 'rajasthan-1',
        name: 'Rajasthan Royal Tour',
        destination: 'Rajasthan',
        duration: '7 Days / 6 Nights',
        price: 34999,
        originalPrice: 42999,
        image: '/images/service_local_trip.png',
        description: 'Explore the land of kings with majestic forts and palaces.',
        highlights: ['Jaipur', 'Udaipur', 'Jodhpur', 'Desert Safari'],
        category: 'domestic',
    },
    {
        id: 'manali-1',
        name: 'Manali Adventure',
        destination: 'Manali',
        duration: '5 Days / 4 Nights',
        price: 22999,
        originalPrice: 27999,
        image: '/images/cta_adventure.png',
        description: 'Adventure in the Himalayas with snow, rafting, and paragliding.',
        highlights: ['Rohtang Pass', 'Solang Valley', 'River rafting', 'Paragliding'],
        category: 'domestic',
    },
    {
        id: 'shimla-1',
        name: 'Shimla Hill Station',
        destination: 'Shimla',
        duration: '4 Days / 3 Nights',
        price: 18999,
        originalPrice: 22999,
        image: '/images/destination_munnar.png',
        description: 'Visit the Queen of Hills with colonial charm and mountain views.',
        highlights: ['Mall Road', 'Kufri', 'Toy Train', 'Christ Church'],
        category: 'domestic',
    },
    {
        id: 'andaman-1',
        name: 'Andaman Island Escape',
        destination: 'Andaman',
        duration: '5 Days / 4 Nights',
        price: 32999,
        originalPrice: 39999,
        image: '/images/destination_kovalam.png',
        description: 'Crystal clear waters and pristine beaches of the Andaman Islands.',
        highlights: ['Havelock Island', 'Cellular Jail', 'Scuba diving', 'Beach camping'],
        category: 'domestic',
    },
    // COMPLETE KERALA TOUR
    {
        id: 'kerala-complete-1',
        name: 'Complete Kerala Tour',
        destination: 'Kerala',
        duration: '7 Days / 6 Nights',
        price: 29999,
        originalPrice: 37999,
        image: '/images/destination_alleppey.png',
        description: 'Experience the best of Kerala - hills, backwaters, beaches, and wildlife.',
        highlights: ['Munnar', 'Thekkady', 'Alleppey', 'Kovalam'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'kerala-honeymoon-1',
        name: 'Kerala Honeymoon Special',
        destination: 'Kerala',
        duration: '6 Days / 5 Nights',
        price: 34999,
        originalPrice: 42999,
        image: '/images/destination_alleppey.png',
        description: 'Romantic getaway with houseboat stay, hill station, and beach resort.',
        highlights: ['Candlelit dinner', 'Houseboat', 'Spa treatments', 'Private tours'],
        category: 'kerala',
    },
    // SPECIAL PACKAGES
    {
        id: 'weekend-munnar',
        name: 'Weekend Getaway Munnar',
        destination: 'Munnar',
        duration: '2 Days / 1 Night',
        price: 4999,
        originalPrice: 6499,
        image: '/images/destination_munnar.png',
        description: 'Quick weekend escape to the misty hills of Munnar.',
        highlights: ['Tea gardens', 'View points', 'Photography', 'Nature walk'],
        category: 'kerala',
    },
    {
        id: 'weekend-wayanad',
        name: 'Weekend Getaway Wayanad',
        destination: 'Wayanad',
        duration: '2 Days / 1 Night',
        price: 5499,
        originalPrice: 6999,
        image: '/images/destination_wayanad.png',
        description: 'Perfect weekend retreat to the green paradise of Wayanad.',
        highlights: ['Edakkal Caves', 'Tree house stay', 'Spice garden', 'Waterfall'],
        category: 'kerala',
    },
    {
        id: 'pilgrimage-kerala',
        name: 'Kerala Temple Tour',
        destination: 'Kerala',
        duration: '4 Days / 3 Nights',
        price: 11999,
        originalPrice: 14999,
        image: '/images/destination_kochi.png',
        description: 'Visit the famous temples of Kerala including Guruvayoor and Sabarimala.',
        highlights: ['Guruvayoor', 'Sabarimala', 'Padmanabhaswamy', 'Kathakali'],
        category: 'kerala',
    },
    {
        id: 'family-kerala',
        name: 'Kerala Family Package',
        destination: 'Kerala',
        duration: '5 Days / 4 Nights',
        price: 24999,
        originalPrice: 29999,
        image: '/images/destination_thekkady.png',
        description: 'Perfect family vacation covering hills, backwaters, and kid-friendly activities.',
        highlights: ['Elephant safari', 'Houseboat', 'Tea factory', 'Spice garden'],
        category: 'kerala',
    },
    {
        id: 'adventure-kerala',
        name: 'Kerala Adventure Package',
        destination: 'Kerala',
        duration: '4 Days / 3 Nights',
        price: 15999,
        originalPrice: 19999,
        image: '/images/cta_adventure.png',
        description: 'Thrilling adventure activities including trekking, rafting, and more.',
        highlights: ['Trekking', 'Bamboo rafting', 'Rock climbing', 'Camping'],
        category: 'kerala',
    },
    {
        id: 'photography-kerala',
        name: 'Kerala Photography Tour',
        destination: 'Kerala',
        duration: '5 Days / 4 Nights',
        price: 18999,
        originalPrice: 22999,
        image: '/images/destination_alleppey.png',
        description: 'Specially designed for photography enthusiasts to capture Gods Own Country.',
        highlights: ['Sunrise shots', 'Wildlife', 'Landscapes', 'Culture'],
        category: 'kerala',
    },
];

export const vehicles: Vehicle[] = [
    {
        id: 'sedan-nonac',
        name: 'Swift Dzire',
        type: 'Non AC',
        category: 'Sedan',
        seatingCapacity: 4,
        pricePerKm: 12,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Comfortable seats', 'Boot space', 'Music system'],
    },
    {
        id: 'sedan-ac',
        name: 'Swift Dzire AC',
        type: 'AC',
        category: 'Sedan',
        seatingCapacity: 4,
        pricePerKm: 14,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Air conditioning', 'Comfortable seats', 'Boot space', 'Music system'],
    },
    {
        id: 'muv-nonac',
        name: 'Maruti Ertiga',
        type: 'Non AC',
        category: 'MUV',
        seatingCapacity: 7,
        pricePerKm: 16,
        image: '/images/vehicle_ertiga.png',
        features: ['7 seater', 'Spacious', 'Luggage space'],
    },
    {
        id: 'muv-ac',
        name: 'Maruti Ertiga AC',
        type: 'AC',
        category: 'MUV',
        seatingCapacity: 7,
        pricePerKm: 18,
        image: '/images/vehicle_ertiga.png',
        features: ['Air conditioning', '7 seater', 'Spacious', 'Luggage space'],
    },
    {
        id: 'suv-nonac',
        name: 'Mahindra Scorpio',
        type: 'Non AC',
        category: 'SUV',
        seatingCapacity: 7,
        pricePerKm: 18,
        image: '/images/vehicle_innova.png',
        features: ['Powerful engine', 'Off-road capable', 'Spacious'],
    },
    {
        id: 'suv-ac',
        name: 'Toyota Innova',
        type: 'AC',
        category: 'SUV',
        seatingCapacity: 7,
        pricePerKm: 22,
        image: '/images/vehicle_innova.png',
        features: ['Premium AC', 'Captain seats', 'Entertainment system', 'Extra comfort'],
    },
    {
        id: 'centica',
        name: 'Hyundai Centica',
        type: 'AC',
        category: 'Centica',
        seatingCapacity: 4,
        pricePerKm: 10,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Fuel efficient', 'Compact', 'AC', 'City friendly'],
    },
    {
        id: '2x3-nonac',
        name: 'Tempo Traveller',
        type: 'Non AC',
        category: '2x3',
        seatingCapacity: 12,
        pricePerKm: 24,
        image: '/images/vehicle_tempo_traveller.png',
        features: ['12 seater', 'Group travel', 'Ample luggage space'],
    },
];

export const services: Service[] = [
    {
        id: 'local',
        name: 'Local Trips',
        description: 'Explore your city with our reliable local cab service',
        icon: 'MapPin',
        type: 'Local',
        image: '/images/service_local_trip.png',
    },
    {
        id: 'intercity',
        name: 'Intercity Travel',
        description: 'Travel between cities in comfort and style',
        icon: 'Route',
        type: 'Intercity',
        image: '/images/service_intercity.png',
    },
    {
        id: 'city-tour',
        name: 'City Tours',
        description: 'Guided city tours with experienced drivers',
        icon: 'Building2',
        type: 'City Tour',
        image: '/images/service_city_tour.png',
    },
    {
        id: 'site-seeing',
        name: 'Site Seeing',
        description: 'Visit popular tourist attractions and landmarks',
        icon: 'Camera',
        type: 'Site Seeing',
        image: '/images/destination_munnar.png',
    },
    {
        id: 'airport',
        name: 'Airport Transfer',
        description: 'Timely and reliable airport pickup and drop',
        icon: 'Plane',
        type: 'Airport',
        image: '/images/service_airport_transfer.png',
    },
    {
        id: 'round-trip',
        name: 'Round Trip',
        description: 'Book for complete round trip journeys with better rates',
        icon: 'RotateCcw',
        type: 'Round Trip',
        image: '/images/destination_alleppey.png',
    },
];

export const categories: Category[] = [
    {
        id: 'car-rental',
        name: 'Car Rental with Driver',
        description: 'Hire a car with experienced driver for any occasion',
        icon: 'Car',
        count: 15,
        image: '/images/vehicle_innova.png',
    },
    {
        id: 'tour-operators',
        name: 'Tour Operators',
        description: 'Professional tour operators for Kerala and beyond',
        icon: 'Users',
        count: 8,
        image: '/images/service_local_trip.png',
    },
    {
        id: 'tour-packages',
        name: 'Tour Packages',
        description: 'Curated tour packages for all destinations',
        icon: 'Package',
        count: 33,
        image: '/images/destination_munnar.png',
    },
    {
        id: 'holiday-packages',
        name: 'Holiday Packages',
        description: 'Special holiday packages for festivals and vacations',
        icon: 'Palmtree',
        count: 12,
        image: '/images/destination_alleppey.png',
    },
];

export const reviews: Review[] = [
    {
        id: '1',
        userName: 'Rahul Menon',
        location: 'Ottapalam',
        rating: 5,
        comment: 'Excellent service! The driver was very professional and the car was spotless. Highly recommend Kerala Tours for any travel needs.',
        date: '2025-12-15',
        helpful: 24,
    },
    {
        id: '2',
        userName: 'Priya Nair',
        location: 'Palakkad',
        rating: 5,
        comment: 'Booked a Munnar trip package. Everything was perfectly arranged. The homestay was beautiful and our driver Raju was amazing!',
        date: '2025-12-10',
        helpful: 18,
    },
    {
        id: '3',
        userName: 'Mohammed Ashraf',
        location: 'Pattambi',
        rating: 4,
        comment: 'Good experience overall. The booking process was smooth and the vehicle arrived on time. Will use again for future trips.',
        date: '2025-12-05',
        helpful: 12,
    },
    {
        id: '4',
        userName: 'Lakshmi Krishnan',
        location: 'Palakkad',
        rating: 5,
        comment: 'We had an amazing family trip to Wayanad. The Innova was very comfortable and the driver knew all the best spots!',
        date: '2025-11-28',
        helpful: 31,
    },
    {
        id: '5',
        userName: 'Arun Kumar',
        location: 'Thrissur',
        rating: 5,
        comment: 'Airport pickup was perfectly timed. Driver was waiting for me even though my flight was delayed. Great customer service!',
        date: '2025-11-20',
        helpful: 15,
    },
    {
        id: '6',
        userName: 'Sreeja Mohan',
        location: 'Kochi',
        rating: 5,
        comment: 'Booked for our honeymoon trip to Munnar and Thekkady. The package was value for money and everything was well organized. Highly recommended!',
        date: '2025-11-15',
        helpful: 28,
    },
    {
        id: '7',
        userName: 'Vijay Shankar',
        location: 'Coimbatore',
        rating: 5,
        comment: 'Used their service for a 5-day Kerala tour. The driver was knowledgeable about all tourist spots and helped us discover hidden gems!',
        date: '2025-11-10',
        helpful: 22,
    },
    {
        id: '8',
        userName: 'Anjali Thomas',
        location: 'Trivandrum',
        rating: 4,
        comment: 'Clean and comfortable vehicle. The booking process via WhatsApp was very convenient. Minor delay on pickup but otherwise great service.',
        date: '2025-11-05',
        helpful: 9,
    },
    {
        id: '9',
        userName: 'Suresh Pillai',
        location: 'Malappuram',
        rating: 5,
        comment: 'Best taxi service in Kerala! Used them multiple times for airport transfers and city tours. Always reliable and professional.',
        date: '2025-10-28',
        helpful: 35,
    },
    {
        id: '10',
        userName: 'Deepa Rajan',
        location: 'Kannur',
        rating: 5,
        comment: 'Organized a group tour for our office colleagues. The team handled everything perfectly - vehicles, accommodation, and sightseeing. Thank you!',
        date: '2025-10-20',
        helpful: 19,
    },
    {
        id: '11',
        userName: 'Anoop Varghese',
        location: 'Kottayam',
        rating: 5,
        comment: 'Excellent backwater trip experience! The houseboat was amazing and our guide was very friendly. Will definitely book again for our next family vacation.',
        date: '2025-10-15',
        helpful: 26,
    },
    {
        id: '12',
        userName: 'Fathima Beevi',
        location: 'Kozhikode',
        rating: 4,
        comment: 'Good service at reasonable prices. The Tempo Traveller was perfect for our family pilgrimage trip. Driver was patient and helpful throughout.',
        date: '2025-10-08',
        helpful: 14,
    },
];

export const photoCategories = [
    { id: 'drive-option', name: 'Drive Options' },
    { id: 'car-seating', name: 'Car Seating' },
    { id: 'capacity', name: 'Seating Capacity' },
    { id: 'rental-type', name: 'Rental Types' },
    { id: 'destinations', name: 'Destinations' },
];

export const stats = {
    totalPackages: 33,
    happyCustomers: 5000,
    yearsExperience: 10,
    vehiclesAvailable: 50,
    destinations: 15,
};
