// Static data for Kerala Tours Travel Application

import { Package, Vehicle, Service, Category, Review, ContactInfo } from '@/types';

export const companyInfo = {
    name: 'Kerala Tours',
    tagline: 'Best Travel Agency',
    slogan: 'From where you are to where you want me to be',
    description: 'We offer best cab services at affordable price. We offer city tours, airport taxi service, round trip cabs, self drive cars etc... more details get in touch with us or book your cab now.',
    locations: ['Kerala Tours', 'Taxi Services', 'Pattambi', 'Palakkad'],
};

export const contactInfo: ContactInfo = {
    phone: '+91 98765 43210',
    whatsapp: '+919876543210',
    email: 'info@keralatours.com',
    address: 'Pattambi, Palakkad, Kerala 679303',
    googleMapsUrl: 'https://maps.google.com/?q=Pattambi,Palakkad,Kerala',
};

export const packages: Package[] = [
    {
        id: 'goa-1',
        name: 'Goa Beach Paradise',
        destination: 'Goa',
        duration: '4 Days / 3 Nights',
        price: 12999,
        originalPrice: 15999,
        image: '/images/destination_kovalam.png',
        description: 'Experience the vibrant beaches, nightlife, and Portuguese heritage of Goa.',
        highlights: ['Beach hopping', 'Water sports', 'Night markets', 'Church visits'],
        category: 'domestic',
        featured: true,
    },
    {
        id: 'kerala-1',
        name: 'Kerala Backwaters',
        destination: 'Kerala',
        duration: '5 Days / 4 Nights',
        price: 14999,
        originalPrice: 18999,
        image: '/images/destination_alleppey.png',
        description: 'Cruise through the serene backwaters and experience Gods Own Country.',
        highlights: ['Houseboat stay', 'Ayurveda spa', 'Tea plantations', 'Wildlife sanctuary'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'munnar-1',
        name: 'Munnar Hill Station',
        destination: 'Munnar',
        duration: '3 Days / 2 Nights',
        price: 8999,
        originalPrice: 10999,
        image: '/images/destination_munnar.png',
        description: 'Escape to the cool hills of Munnar with lush tea gardens and misty mountains.',
        highlights: ['Tea gardens', 'Mattupetty Dam', 'Echo Point', 'Flower gardens'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'mysore-1',
        name: 'Mysore Royal Heritage',
        destination: 'Mysore',
        duration: '3 Days / 2 Nights',
        price: 9999,
        originalPrice: 12999,
        image: '/images/destination_kochi.png',
        description: 'Discover the royal heritage and magnificent palaces of Mysore.',
        highlights: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens', 'Zoo'],
        category: 'outside-kerala',
    },
    {
        id: 'bekal-1',
        name: 'Bekal Fort & Beach',
        destination: 'Bekal',
        duration: '2 Days / 1 Night',
        price: 5999,
        originalPrice: 7999,
        image: '/images/hero_backwaters.png',
        description: 'Visit the historic Bekal Fort and enjoy pristine beaches.',
        highlights: ['Bekal Fort', 'Beach resort', 'Backwaters', 'Local cuisine'],
        category: 'kerala',
    },
    {
        id: 'kaspad-1',
        name: 'Kaspad Adventure',
        destination: 'Kaspad',
        duration: '2 Days / 1 Night',
        price: 4999,
        originalPrice: 6999,
        image: '/images/destination_thekkady.png',
        description: 'Experience the untouched beauty and adventure activities.',
        highlights: ['Trekking', 'Nature walks', 'Local villages', 'Photography'],
        category: 'kerala',
    },
    {
        id: 'wayanad-1',
        name: 'Wayanad Wildlife',
        destination: 'Wayanad',
        duration: '3 Days / 2 Nights',
        price: 11999,
        originalPrice: 14999,
        image: '/images/destination_wayanad.png',
        description: 'Explore the wildlife sanctuaries and natural beauty of Wayanad.',
        highlights: ['Wildlife safari', 'Edakkal Caves', 'Bamboo forest', 'Spice gardens'],
        category: 'kerala',
    },
    {
        id: 'ooty-1',
        name: 'Ooty Queen of Hills',
        destination: 'Ooty',
        duration: '4 Days / 3 Nights',
        price: 13999,
        originalPrice: 16999,
        image: '/images/cta_adventure.png',
        description: 'Visit the Queen of Hill Stations with toy train and botanical gardens.',
        highlights: ['Toy train ride', 'Botanical Garden', 'Ooty Lake', 'Tea factory'],
        category: 'outside-kerala',
    },
];

export const vehicles: Vehicle[] = [
    {
        id: 'sedan-nonac',
        name: 'Swift Dzire',
        type: 'Non AC',
        category: 'Sedan',
        seatingCapacity: 4,
        pricePerKm: 12,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Comfortable seats', 'Boot space', 'Music system'],
    },
    {
        id: 'sedan-ac',
        name: 'Swift Dzire AC',
        type: 'AC',
        category: 'Sedan',
        seatingCapacity: 4,
        pricePerKm: 14,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Air conditioning', 'Comfortable seats', 'Boot space', 'Music system'],
    },
    {
        id: 'muv-nonac',
        name: 'Maruti Ertiga',
        type: 'Non AC',
        category: 'MUV',
        seatingCapacity: 7,
        pricePerKm: 16,
        image: '/images/vehicle_ertiga.png',
        features: ['7 seater', 'Spacious', 'Luggage space'],
    },
    {
        id: 'muv-ac',
        name: 'Maruti Ertiga AC',
        type: 'AC',
        category: 'MUV',
        seatingCapacity: 7,
        pricePerKm: 18,
        image: '/images/vehicle_ertiga.png',
        features: ['Air conditioning', '7 seater', 'Spacious', 'Luggage space'],
    },
    {
        id: 'suv-nonac',
        name: 'Mahindra Scorpio',
        type: 'Non AC',
        category: 'SUV',
        seatingCapacity: 7,
        pricePerKm: 18,
        image: '/images/vehicle_innova.png',
        features: ['Powerful engine', 'Off-road capable', 'Spacious'],
    },
    {
        id: 'suv-ac',
        name: 'Toyota Innova',
        type: 'AC',
        category: 'SUV',
        seatingCapacity: 7,
        pricePerKm: 22,
        image: '/images/vehicle_innova.png',
        features: ['Premium AC', 'Captain seats', 'Entertainment system', 'Extra comfort'],
    },
    {
        id: 'centica',
        name: 'Hyundai Centica',
        type: 'AC',
        category: 'Centica',
        seatingCapacity: 4,
        pricePerKm: 10,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Fuel efficient', 'Compact', 'AC', 'City friendly'],
    },
    {
        id: '2x3-nonac',
        name: 'Tempo Traveller',
        type: 'Non AC',
        category: '2x3',
        seatingCapacity: 12,
        pricePerKm: 24,
        image: '/images/vehicle_tempo_traveller.png',
        features: ['12 seater', 'Group travel', 'Ample luggage space'],
    },
];

export const services: Service[] = [
    {
        id: 'local',
        name: 'Local Trips',
        description: 'Explore your city with our reliable local cab service',
        icon: 'MapPin',
        type: 'Local',
        image: '/images/service_local_trip.png',
    },
    {
        id: 'intercity',
        name: 'Intercity Travel',
        description: 'Travel between cities in comfort and style',
        icon: 'Route',
        type: 'Intercity',
        image: '/images/service_intercity.png',
    },
    {
        id: 'city-tour',
        name: 'City Tours',
        description: 'Guided city tours with experienced drivers',
        icon: 'Building2',
        type: 'City Tour',
        image: '/images/service_city_tour.png',
    },
    {
        id: 'site-seeing',
        name: 'Site Seeing',
        description: 'Visit popular tourist attractions and landmarks',
        icon: 'Camera',
        type: 'Site Seeing',
        image: '/images/destination_munnar.png',
    },
    {
        id: 'airport',
        name: 'Airport Transfer',
        description: 'Timely and reliable airport pickup and drop',
        icon: 'Plane',
        type: 'Airport',
        image: '/images/service_airport_transfer.png',
    },
    {
        id: 'round-trip',
        name: 'Round Trip',
        description: 'Book for complete round trip journeys with better rates',
        icon: 'RotateCcw',
        type: 'Round Trip',
        image: '/images/destination_alleppey.png',
    },
];

export const categories: Category[] = [
    {
        id: 'car-rental',
        name: 'Car Rental with Driver',
        description: 'Hire a car with experienced driver for any occasion',
        icon: 'Car',
        count: 15,
        image: '/images/vehicle_innova.png',
    },
    {
        id: 'tour-operators',
        name: 'Tour Operators',
        description: 'Professional tour operators for Kerala and beyond',
        icon: 'Users',
        count: 8,
        image: '/images/service_local_trip.png',
    },
    {
        id: 'tour-packages',
        name: 'Tour Packages',
        description: 'Curated tour packages for all destinations',
        icon: 'Package',
        count: 33,
        image: '/images/destination_munnar.png',
    },
    {
        id: 'holiday-packages',
        name: 'Holiday Packages',
        description: 'Special holiday packages for festivals and vacations',
        icon: 'Palmtree',
        count: 12,
        image: '/images/destination_alleppey.png',
    },
];

export const reviews: Review[] = [
    {
        id: '1',
        userName: 'Rahul Menon',
        location: 'Ottapalam',
        rating: 5,
        comment: 'Excellent service! The driver was very professional and the car was spotless. Highly recommend Kerala Tours for any travel needs.',
        date: '2025-12-15',
        helpful: 24,
    },
    {
        id: '2',
        userName: 'Priya Nair',
        location: 'Palakkad',
        rating: 5,
        comment: 'Booked a Munnar trip package. Everything was perfectly arranged. The homestay was beautiful and our driver Raju was amazing!',
        date: '2025-12-10',
        helpful: 18,
    },
    {
        id: '3',
        userName: 'Mohammed Ashraf',
        location: 'Kaskal',
        rating: 4,
        comment: 'Good experience overall. The booking process was smooth and the vehicle arrived on time. Will use again for future trips.',
        date: '2025-12-05',
        helpful: 12,
    },
    {
        id: '4',
        userName: 'Lakshmi Krishnan',
        location: 'Pattambi',
        rating: 5,
        comment: 'We had an amazing family trip to Wayanad. The Innova was very comfortable and the driver knew all the best spots!',
        date: '2025-11-28',
        helpful: 31,
    },
    {
        id: '5',
        userName: 'Arun Kumar',
        location: 'Thrissur',
        rating: 5,
        comment: 'Airport pickup was perfectly timed. Driver was waiting for me even though my flight was delayed. Great customer service!',
        date: '2025-11-20',
        helpful: 15,
    },
];

export const photoCategories = [
    { id: 'drive-option', name: 'Drive Options' },
    { id: 'car-seating', name: 'Car Seating' },
    { id: 'capacity', name: 'Seating Capacity' },
    { id: 'rental-type', name: 'Rental Types' },
    { id: 'destinations', name: 'Destinations' },
];

export const stats = {
    totalPackages: 33,
    happyCustomers: 5000,
    yearsExperience: 10,
    vehiclesAvailable: 50,
    destinations: 15,
};
