// Static data for Kerala Tours Travel Application

import { Package, Vehicle, Service, Category, Review, ContactInfo } from '@/types';

export const companyInfo = {
    name: 'Golden Globe Tour Taxi Service',
    tagline: 'Best Travel Agency',
    slogan: 'From where you are to where you want me to be',
    description: 'We offer best cab services at affordable price. We offer city tours, airport taxi service, round trip cabs, self drive cars etc... more details get in touch with us or book your cab now.',
    locations: ['Golden Globe', 'Taxi Services', 'Pattambi', 'Palakkad'],
};

export const contactInfo: ContactInfo = {
    phone: '+91 9061883919',
    whatsapp: '919061883919',
    email: 'mdraffi114@gmail.com',
    owner: 'Muhammed Raffi R',
    address: 'Pallath house, Maruthur post, Pattambi, Palakkad district - 679306',
    locationDescription: 'Infront of Sevana Hospital, near Pattambi',
    googleMapsUrl: 'https://maps.app.goo.gl/nC2GSje1pVNpuHrDA',
};

export const packages: Package[] = [
    // KERALA PACKAGES
    {
        id: 'alleppey-backwaters-houseboat',
        name: 'Kerala Backwaters Houseboat',
        destination: 'Alleppey',
        duration: '3 Days / 2 Nights',
        price: 12999,
        originalPrice: 15999,
        image: '/images/destination_alleppey.png',
        description: 'Cruise through the serene backwaters on a traditional houseboat. Experience authentic Kerala cuisine and village life.',
        highlights: ['Houseboat stay', 'Village visits', 'Kerala cuisine', 'Sunset views'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'munnar-tea-gardens',
        name: 'Munnar Tea Garden Escape',
        destination: 'Munnar',
        duration: '3 Days / 2 Nights',
        price: 8999,
        originalPrice: 10999,
        image: '/images/destination_munnar.png',
        description: 'Escape to the cool hills of Munnar with lush tea gardens and misty mountains.',
        highlights: ['Tea gardens', 'Mattupetty Dam', 'Echo Point', 'Flower gardens'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'wayanad-wildlife-adventure',
        name: 'Wayanad Wildlife Adventure',
        destination: 'Wayanad',
        duration: '3 Days / 2 Nights',
        price: 11999,
        originalPrice: 14999,
        image: '/images/destination_wayanad.png',
        description: 'Explore the wildlife sanctuaries and natural beauty of Wayanad.',
        highlights: ['Wildlife safari', 'Edakkal Caves', 'Bamboo forest', 'Spice gardens'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'thekkady-periyar-safari',
        name: 'Thekkady Periyar Safari',
        destination: 'Thekkady',
        duration: '2 Days / 1 Night',
        price: 7999,
        originalPrice: 9999,
        image: '/images/destination_thekkady.png',
        description: 'Experience the famous Periyar Tiger Reserve with boat safari and spice plantation visits.',
        highlights: ['Tiger Reserve', 'Boat safari', 'Spice garden', 'Elephant ride'],
        category: 'kerala',
    },
    {
        id: 'kovalam-beach-holiday',
        name: 'Kovalam Beach Holiday',
        destination: 'Kovalam',
        duration: '3 Days / 2 Nights',
        price: 9999,
        originalPrice: 12999,
        image: '/images/destination_kovalam.png',
        description: 'Relax at the famous lighthouse beach and enjoy Ayurvedic treatments.',
        highlights: ['Lighthouse Beach', 'Ayurveda spa', 'Seafood', 'Water sports'],
        category: 'kerala',
    },
    {
        id: 'kochi-heritage-walk',
        name: 'Kochi Heritage Walk',
        destination: 'Kochi',
        duration: '2 Days / 1 Night',
        price: 5999,
        originalPrice: 7999,
        image: '/images/destination_kochi.png',
        description: 'Explore the historic Fort Kochi with Chinese fishing nets and colonial architecture.',
        highlights: ['Fort Kochi', 'Chinese nets', 'Jewish Synagogue', 'Spice markets'],
        category: 'kerala',
    },
    {
        id: 'bekal-fort-beach',
        name: 'Bekal Fort & Beach',
        destination: 'Bekal',
        duration: '2 Days / 1 Night',
        price: 5999,
        originalPrice: 7999,
        image: '/images/package_bekal_fort.png',
        description: 'Visit the historic Bekal Fort and enjoy pristine beaches.',
        highlights: ['Bekal Fort', 'Beach resort', 'Backwaters', 'Kerala cuisine'],
        category: 'kerala',
    },
    {
        id: 'athirapally-waterfalls',
        name: 'Athirapally Falls Trip',
        destination: 'Athirapally',
        duration: '1 Day',
        price: 2999,
        originalPrice: 3999,
        image: '/images/package_athirapally_falls.png',
        description: 'Visit the majestic Athirapally waterfalls - the Niagara of India.',
        highlights: ['Waterfalls', 'Vazhachal Falls', 'Nature walk', 'Photography'],
        category: 'kerala',
    },
    {
        id: 'kumarakom-bird-sanctuary',
        name: 'Kumarakom Bird Sanctuary',
        destination: 'Kumarakom',
        duration: '2 Days / 1 Night',
        price: 6999,
        originalPrice: 8999,
        image: '/images/package_kumarakom_birds.png',
        description: 'Explore the famous bird sanctuary and enjoy houseboat experiences.',
        highlights: ['Bird watching', 'Houseboat', 'Fishing', 'Village life'],
        category: 'kerala',
    },
    {
        id: 'vagamon-hills-retreat',
        name: 'Vagamon Hills Retreat',
        destination: 'Vagamon',
        duration: '2 Days / 1 Night',
        price: 5499,
        originalPrice: 6999,
        image: '/images/package_vagamon_hills.png',
        description: 'Experience the serene meadows and pine forests of Vagamon.',
        highlights: ['Pine forests', 'Paragliding', 'Tea estates', 'Trekking'],
        category: 'kerala',
    },
    // GOA PACKAGE
    {
        id: 'goa-beach-paradise',
        name: 'Goa Beach Paradise',
        destination: 'Goa',
        duration: '4 Days / 3 Nights',
        price: 14999,
        originalPrice: 18999,
        image: '/images/package_goa_beach.png',
        description: 'Experience the vibrant beaches, nightlife, and Portuguese heritage of Goa.',
        highlights: ['Beach hopping', 'Water sports', 'Night markets', 'Church visits'],
        category: 'domestic',
        featured: true,
    },
    {
        id: 'north-goa-adventure',
        name: 'North Goa Adventure',
        destination: 'Goa',
        duration: '3 Days / 2 Nights',
        price: 11999,
        originalPrice: 14999,
        image: '/images/package_goa_beach.png',
        description: 'Explore the famous beaches and nightlife of North Goa.',
        highlights: ['Baga Beach', 'Calangute', 'Anjuna Market', 'Cruise'],
        category: 'domestic',
    },
    // OUTSIDE KERALA PACKAGES
    {
        id: 'mysore-palace-heritage',
        name: 'Mysore Royal Heritage',
        destination: 'Mysore',
        duration: '3 Days / 2 Nights',
        price: 9999,
        originalPrice: 12999,
        image: '/images/package_mysore_palace.png',
        description: 'Discover the royal heritage and magnificent palaces of Mysore.',
        highlights: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens', 'Zoo'],
        category: 'outside-kerala',
        featured: true,
    },
    {
        id: 'ooty-nilgiri-hills',
        name: 'Ooty Queen of Hills',
        destination: 'Ooty',
        duration: '4 Days / 3 Nights',
        price: 13999,
        originalPrice: 16999,
        image: '/images/package_ooty_toy_train.png',
        description: 'Visit the Queen of Hill Stations with toy train and botanical gardens.',
        highlights: ['Toy train ride', 'Botanical Garden', 'Ooty Lake', 'Tea factory'],
        category: 'outside-kerala',
    },
    {
        id: 'kodaikanal-princess-hills',
        name: 'Kodaikanal Princess of Hills',
        destination: 'Kodaikanal',
        duration: '3 Days / 2 Nights',
        price: 10999,
        originalPrice: 13999,
        image: '/images/package_kodaikanal_lake.png',
        description: 'Explore the Princess of Hill Stations with its star-shaped lake.',
        highlights: ['Kodai Lake', 'Coakers Walk', 'Pillar Rocks', 'Pine Forest'],
        category: 'outside-kerala',
    },
    {
        id: 'bangalore-tech-city',
        name: 'Bangalore Tech City Tour',
        destination: 'Bangalore',
        duration: '2 Days / 1 Night',
        price: 7999,
        originalPrice: 9999,
        image: '/images/package_bangalore_gardens.png',
        description: 'Explore the Silicon Valley of India with gardens and modern attractions.',
        highlights: ['Lalbagh Garden', 'Cubbon Park', 'Wonderla', 'Shopping'],
        category: 'outside-kerala',
    },
    {
        id: 'coorg-coffee-plantations',
        name: 'Coorg Coffee Estate',
        destination: 'Coorg',
        duration: '3 Days / 2 Nights',
        price: 12999,
        originalPrice: 15999,
        image: '/images/package_coorg_coffee.png',
        description: 'The Scotland of India with coffee plantations and waterfalls.',
        highlights: ['Coffee estates', 'Abbey Falls', 'Dubare Camp', 'Tibetan Camp'],
        category: 'outside-kerala',
        featured: true,
    },
    {
        id: 'rameshwaram-temple-pilgrimage',
        name: 'Rameshwaram Pilgrimage',
        destination: 'Rameshwaram',
        duration: '3 Days / 2 Nights',
        price: 8999,
        originalPrice: 10999,
        image: '/images/package_rameshwaram_temple.png',
        description: 'Visit one of the holiest Hindu temples on the island.',
        highlights: ['Temple visit', 'Pamban Bridge', 'Dhanushkodi', 'Beach'],
        category: 'pilgrimage',
    },
    {
        id: 'madurai-meenakshi-temple',
        name: 'Madurai Temple Tour',
        destination: 'Madurai',
        duration: '2 Days / 1 Night',
        price: 6999,
        originalPrice: 8999,
        image: '/images/package_madurai_temple.png',
        description: 'Visit the magnificent Meenakshi Temple and explore ancient Madurai.',
        highlights: ['Meenakshi Temple', 'Thirumalai Palace', 'Gandhi Museum', 'Local food'],
        category: 'pilgrimage',
    },
    {
        id: 'pondicherry-french-town',
        name: 'Pondicherry French Colony',
        destination: 'Pondicherry',
        duration: '3 Days / 2 Nights',
        price: 9999,
        originalPrice: 11999,
        image: '/images/package_pondicherry_french.png',
        description: 'Experience the French colonial charm and beautiful beaches.',
        highlights: ['French Colony', 'Auroville', 'Paradise Beach', 'Cafes'],
        category: 'outside-kerala',
    },
    // DOMESTIC TOUR PACKAGES
    {
        id: 'andaman-islands-escape',
        name: 'Andaman Island Escape',
        destination: 'Andaman',
        duration: '5 Days / 4 Nights',
        price: 32999,
        originalPrice: 39999,
        image: '/images/package_andaman_islands.png',
        description: 'Crystal clear waters and pristine beaches of the Andaman Islands.',
        highlights: ['Havelock Island', 'Cellular Jail', 'Scuba diving', 'Beach camping'],
        category: 'domestic',
    },
    // COMPLETE KERALA TOUR
    {
        id: 'complete-kerala-tour',
        name: 'Complete Kerala Tour',
        destination: 'Kerala',
        duration: '7 Days / 6 Nights',
        price: 29999,
        originalPrice: 37999,
        image: '/images/package_complete_kerala.png',
        description: 'Experience the best of Kerala - hills, backwaters, beaches, and wildlife.',
        highlights: ['Munnar', 'Thekkady', 'Alleppey', 'Kovalam'],
        category: 'kerala',
        featured: true,
    },
    {
        id: 'kerala-honeymoon-package',
        name: 'Kerala Honeymoon Special',
        destination: 'Kerala',
        duration: '6 Days / 5 Nights',
        price: 34999,
        originalPrice: 42999,
        image: '/images/package_kerala_honeymoon.png',
        description: 'Romantic getaway with houseboat stay, hill station, and beach resort.',
        highlights: ['Candlelit dinner', 'Houseboat', 'Spa treatments', 'Private tours'],
        category: 'kerala',
    },
    // SPECIAL PACKAGES
    {
        id: 'munnar-weekend-getaway',
        name: 'Weekend Getaway Munnar',
        destination: 'Munnar',
        duration: '2 Days / 1 Night',
        price: 4999,
        originalPrice: 6499,
        image: '/images/destination_munnar.png',
        description: 'Quick weekend escape to the misty hills of Munnar.',
        highlights: ['Tea gardens', 'View points', 'Photography', 'Nature walk'],
        category: 'kerala',
    },
    {
        id: 'wayanad-weekend-getaway',
        name: 'Weekend Getaway Wayanad',
        destination: 'Wayanad',
        duration: '2 Days / 1 Night',
        price: 5499,
        originalPrice: 6999,
        image: '/images/destination_wayanad.png',
        description: 'Perfect weekend retreat to the green paradise of Wayanad.',
        highlights: ['Edakkal Caves', 'Tree house stay', 'Spice garden', 'Waterfall'],
        category: 'kerala',
    },
    {
        id: 'kerala-temple-circuit',
        name: 'Kerala Temple Tour',
        destination: 'Kerala',
        duration: '4 Days / 3 Nights',
        price: 11999,
        originalPrice: 14999,
        image: '/images/destination_kochi.png',
        description: 'Visit the famous temples of Kerala including Guruvayoor and Sabarimala.',
        highlights: ['Guruvayoor', 'Sabarimala', 'Padmanabhaswamy', 'Kathakali'],
        category: 'kerala',
    },
    {
        id: 'kerala-family-package',
        name: 'Kerala Family Package',
        destination: 'Kerala',
        duration: '5 Days / 4 Nights',
        price: 24999,
        originalPrice: 29999,
        image: '/images/destination_thekkady.png',
        description: 'Perfect family vacation covering hills, backwaters, and kid-friendly activities.',
        highlights: ['Elephant safari', 'Houseboat', 'Tea factory', 'Spice garden'],
        category: 'kerala',
    },
    {
        id: 'kerala-adventure-package',
        name: 'Kerala Adventure Package',
        destination: 'Kerala',
        duration: '4 Days / 3 Nights',
        price: 15999,
        originalPrice: 19999,
        image: '/images/cta_adventure.png',
        description: 'Thrilling adventure activities including trekking, rafting, and more.',
        highlights: ['Trekking', 'Bamboo rafting', 'Rock climbing', 'Camping'],
        category: 'kerala',
    },
    {
        id: 'kerala-photography-tour',
        name: 'Kerala Photography Tour',
        destination: 'Kerala',
        duration: '5 Days / 4 Nights',
        price: 18999,
        originalPrice: 22999,
        image: '/images/destination_alleppey.png',
        description: 'Specially designed for photography enthusiasts to capture Gods Own Country.',
        highlights: ['Sunrise shots', 'Wildlife', 'Landscapes', 'Culture'],
        category: 'kerala',
    },
    // PILGRIMAGE PACKAGES
    {
        id: 'tirupati-balaji-darshan',
        name: 'Tirupati Balaji Darshan from Kerala',
        destination: 'Tirupati',
        duration: '3 Days / 2 Nights',
        price: 12999,
        originalPrice: 15999,
        image: '/images/package_tirupati_balaji.png',
        description: 'Comfortable pilgrimage tour from Kerala to the sacred Tirupati Venkateswara Temple, one of the richest and most visited temples in the world.',
        highlights: ['Balaji Temple', 'Free Darshan', 'Tirumala Hills', 'Laddu Prasadam'],
        category: 'pilgrimage',
        featured: true,
    },
    {
        id: 'velankanni-basilica-tour',
        name: 'Velankanni Basilica Tour',
        destination: 'Velankanni',
        duration: '2 Days / 1 Night',
        price: 7999,
        originalPrice: 9999,
        image: '/images/package_velankanni_church.png',
        description: 'Visit the renowned Basilica of Our Lady of Good Health in Velankanni, Tamil Nadu.',
        highlights: ['Velankanni Church', 'Beach', 'Museum', 'Morning Mass'],
        category: 'pilgrimage',
    },
    {
        id: 'sabarimala-ayyappa-pilgrimage',
        name: 'Sabarimala Ayyappa Darshan',
        destination: 'Sabarimala',
        duration: '2 Days / 1 Night',
        price: 6999,
        originalPrice: 8999,
        image: '/images/package_sabarimala_temple.png',
        description: 'Sacred pilgrimage to Lord Ayyappa temple in the Western Ghats (seasonal).',
        highlights: ['Ayyappa Temple', 'Pathanamthitta', 'Pamba River', 'Neyyar Dam'],
        category: 'pilgrimage',
    },
    {
        id: 'guruvayur-krishna-temple',
        name: 'Guruvayur Sri Krishna Temple',
        destination: 'Guruvayur',
        duration: '1 Day',
        price: 2999,
        originalPrice: 3999,
        image: '/images/pilgrimage_guruvayur.png',
        description: 'Visit the sacred Guruvayur Sri Krishna Temple, known as Dwaraka of the South. Fourth largest temple in India.',
        highlights: ['Sri Krishna Temple', 'Parthasarathy Temple', 'Elephant Sanctuary', 'Temple rituals'],
        category: 'pilgrimage',
        featured: true,
    },
    {
        id: 'padmanabhaswamy-temple-trivandrum',
        name: 'Padmanabhaswamy Temple Trivandrum',
        destination: 'Trivandrum',
        duration: '1 Day',
        price: 1999,
        originalPrice: 2999,
        image: '/images/pilgrimage_padmanabhaswamy.png',
        description: 'Visit one of the 108 Divyadesams and the richest temple in India. 5000 years old temple dedicated to Lord Vishnu.',
        highlights: ['Padmanabhaswamy Temple', 'Fort area', 'Temple architecture', 'Padmatheertham'],
        category: 'pilgrimage',
        featured: true,
    },
    {
        id: 'thrissur-temple-circuit',
        name: 'Thrissur Temple Circuit',
        destination: 'Thrissur',
        duration: '2 Days / 1 Night',
        price: 4999,
        originalPrice: 6499,
        image: '/images/pilgrimage_thrissur.png',
        description: 'Cultural capital of Kerala with Vadakkumnathan Temple, Thiruvambadi Sri Krishna Temple during Thrissur Pooram season.',
        highlights: ['Vadakkumnathan Temple', 'Thrissur Pooram', 'Cultural programs', 'Kerala Kalamandalam'],
        category: 'pilgrimage',
    },
    {
        id: 'attukal-bhagavathy-temple',
        name: 'Attukal Bhagavathy Temple',
        destination: 'Trivandrum',
        duration: '1 Day',
        price: 1999,
        originalPrice: 2999,
        image: '/images/pilgrimage_attukal.png',
        description: 'Sabarimala of Women - Famous for Attukal Pongala festival with Guinness Record for largest women gathering.',
        highlights: ['Attukal Temple', 'Pongala festival', 'Temple rituals', 'City tour'],
        category: 'pilgrimage',
    },
    {
        id: 'chottanikkara-bhagavathy-temple',
        name: 'Chottanikkara Bhagavathy Temple',
        destination: 'Ernakulam',
        duration: '1 Day',
        price: 2499,
        originalPrice: 3499,
        image: '/images/pilgrimage_chottanikkara.png',
        description: 'Famous temple of Raja Rajeshwari Devi worshipped as Saraswati, Bhadrakali, and Durga at different times.',
        highlights: ['Bhagavathy Temple', 'Triple deity worship', 'Makam Thozhal festival', 'Dasara celebrations'],
        category: 'pilgrimage',
    },
    {
        id: 'ambalapuzha-krishna-temple',
        name: 'Ambalapuzha Sri Krishna Temple',
        destination: 'Alleppey',
        duration: '1 Day',
        price: 2999,
        originalPrice: 3999,
        image: '/images/pilgrimage_ambalapuzha.png',
        description: 'One of seven great Vaishnava temples in Travancore. Famous for Paal Payasam offering.',
        highlights: ['Krishna Temple', 'Paal Payasam', 'Water festival', 'Backwaters'],
        category: 'pilgrimage',
    },
    {
        id: 'ettumanoor-mahadeva-temple',
        name: 'Ettumanoor Mahadeva Temple',
        destination: 'Kottayam',
        duration: '1 Day',
        price: 2499,
        originalPrice: 3499,
        image: '/images/pilgrimage_ettumanoor.png',
        description: 'Celebrated Shiva temple with exceptional murals and woodcarvings. Famous for Ezhara Ponnana (golden elephants).',
        highlights: ['Mahadeva Temple', 'Ancient murals', 'Golden elephants', 'Ezharaponnaana festival'],
        category: 'pilgrimage',
    },
    {
        id: 'vaikom-mahadeva-temple',
        name: 'Vaikom Mahadeva Temple',
        destination: 'Vaikom',
        duration: '1 Day',
        price: 2999,
        originalPrice: 3999,
        image: '/images/pilgrimage_vaikom.png',
        description: 'Ancient Shiva temple built by Parasurama. Historical significance with Vaikom Satyagraha movement.',
        highlights: ['Mahadeva Temple', 'Vembanad Lake', 'Backwater tour', 'Historical importance'],
        category: 'pilgrimage',
    },
    {
        id: 'thirunelly-temple-wayanad',
        name: 'Thirunelly Temple Wayanad',
        destination: 'Wayanad',
        duration: '1 Day',
        price: 3499,
        originalPrice: 4499,
        image: '/images/pilgrimage_thirunelly.png',
        description: 'Ancient Vishnu temple in beautiful valley beneath Brahmagiri hills. Also called Sahyamalak Kshetra.',
        highlights: ['Maha Vishnu Temple', 'Brahmagiri hills', 'Forest location', 'Ancient village ruins'],
        category: 'pilgrimage',
    },
    {
        id: 'mannarsala-nagaraja-temple',
        name: 'Mannarsala Nagaraja Temple',
        destination: 'Alleppey',
        duration: '1 Day',
        price: 2999,
        originalPrice: 3999,
        image: '/images/pilgrimage_mannarsala.png',
        description: 'Famous serpent temple with 30,000 snake idols. Only temple in Kerala with a female priestess.',
        highlights: ['Nagaraja Temple', 'Serpent worship', 'Aayilyam festival', 'Forest grove'],
        category: 'pilgrimage',
    },
    {
        id: 'thiruvalla-vallabha-temple',
        name: 'Sri Vallabha Temple Thiruvalla',
        destination: 'Pathanamthitta',
        duration: '1 Day',
        price: 2499,
        originalPrice: 3499,
        image: '/images/pilgrimage_thiruvalla.png',
        description: 'One among 108 Divya Kshetrams dedicated to Lord Vishnu. Famous for daily Kathakali performances.',
        highlights: ['Vallabha Temple', 'Kathakali performances', 'Granite flagstaff', 'Traditional rituals'],
        category: 'pilgrimage',
    },
    {
        id: 'malayalapuzha-devi-temple',
        name: 'Malayalapuzha Devi Temple',
        destination: 'Pathanamthitta',
        duration: '1 Day',
        price: 2499,
        originalPrice: 3499,
        image: '/images/pilgrimage_malayalapuzha.png',
        description: '3000 years old Bhadrakali temple near Pathanamthitta. Famous for Satha Kodi Archana ritual.',
        highlights: ['Bhadrakali Temple', 'Ancient architecture', 'Wall paintings', 'Weekly darshan'],
        category: 'pilgrimage',
    },
    {
        id: 'kottayam-temple-circuit',
        name: 'Kottayam Temple Circuit',
        destination: 'Kottayam',
        duration: '1 Day',
        price: 2999,
        originalPrice: 3999,
        image: '/images/pilgrimage_kottayam.png',
        description: 'Visit Thirunakkara Mahadeva Temple, Pallippurathu Kavu, and other famous temples in Kottayam.',
        highlights: ['Multiple temples', 'Syrian churches', 'Mosques', 'Cultural diversity'],
        category: 'pilgrimage',
    },
    {
        id: 'sarkara-devi-temple-varkala',
        name: 'Sarkara Devi Temple Varkala',
        destination: 'Varkala',
        duration: '1 Day',
        price: 2499,
        originalPrice: 3499,
        image: '/images/pilgrimage_sarkara.png',
        description: 'Major Bhadrakali temple near Varkala with unique origin legend. Important pilgrimage destination.',
        highlights: ['Sarkara Devi', 'Temple architecture', 'Varkala beach', 'Local legends'],
        category: 'pilgrimage',
    },
    {
        id: 'niranam-st-marys-church',
        name: 'St. Marys Church Niranam',
        destination: 'Pathanamthitta',
        duration: '1 Day',
        price: 2499,
        originalPrice: 3499,
        image: '/images/pilgrimage_niranam.png',
        description: 'One of the oldest churches in world founded by St. Thomas in 54 AD. Contains relics of St. Thomas.',
        highlights: ['Ancient church', 'St. Thomas relics', 'Granite cross', 'Christian heritage'],
        category: 'pilgrimage',
    },
    {
        id: 'kuravilangad-st-marys-church',
        name: 'St. Marys Church Kuravilangad',
        destination: 'Kottayam',
        duration: '1 Day',
        price: 2499,
        originalPrice: 3499,
        image: '/images/pilgrimage_kuravilangad.png',
        description: 'Martha Mariam Church built in 105 AD with miraculous spring. 48 feet granite cross from 1597.',
        highlights: ['Ancient church', 'Granite cross', 'Moonnu Nompu festival', 'German bells'],
        category: 'pilgrimage',
    },
    {
        id: 'kaduvayil-juma-masjid',
        name: 'Kaduvayil Juma Masjid',
        destination: 'Varkala',
        duration: '1 Day',
        price: 1999,
        originalPrice: 2999,
        image: '/images/pilgrimage_kaduvayil.png',
        description: 'Important Sunni Muslim pilgrimage site dedicated to Saint Kaduvayil Thangal. Symbol of religious harmony.',
        highlights: ['Juma Masjid', 'Religious harmony', 'Beautiful architecture', 'Orphanage & college'],
        category: 'pilgrimage',
    },
];

export const vehicles: Vehicle[] = [
    {
        id: 'sedan-nonac',
        name: 'Swift Dzire',
        type: 'Non AC',
        category: 'Sedan',
        seatingCapacity: 4,
        pricePerKm: 12,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Comfortable seats', 'Boot space', 'Music system'],
    },
    {
        id: 'sedan-ac',
        name: 'Swift Dzire AC',
        type: 'AC',
        category: 'Sedan',
        seatingCapacity: 4,
        pricePerKm: 14,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Air conditioning', 'Comfortable seats', 'Boot space', 'Music system'],
    },
    {
        id: 'muv-nonac',
        name: 'Maruti Ertiga',
        type: 'Non AC',
        category: 'MUV',
        seatingCapacity: 7,
        pricePerKm: 16,
        image: '/images/vehicle_ertiga.png',
        features: ['7 seater', 'Spacious', 'Luggage space'],
    },
    {
        id: 'muv-ac',
        name: 'Maruti Ertiga AC',
        type: 'AC',
        category: 'MUV',
        seatingCapacity: 7,
        pricePerKm: 18,
        image: '/images/vehicle_ertiga.png',
        features: ['Air conditioning', '7 seater', 'Spacious', 'Luggage space'],
    },
    {
        id: 'suv-nonac',
        name: 'Mahindra Scorpio',
        type: 'Non AC',
        category: 'SUV',
        seatingCapacity: 7,
        pricePerKm: 18,
        image: '/images/vehicle_innova.png',
        features: ['Powerful engine', 'Off-road capable', 'Spacious'],
    },
    {
        id: 'suv-ac',
        name: 'Toyota Innova',
        type: 'AC',
        category: 'SUV',
        seatingCapacity: 7,
        pricePerKm: 22,
        image: '/images/vehicle_innova.png',
        features: ['Premium AC', 'Captain seats', 'Entertainment system', 'Extra comfort'],
    },
    {
        id: 'centica',
        name: 'Hyundai Centica',
        type: 'AC',
        category: 'Centica',
        seatingCapacity: 4,
        pricePerKm: 10,
        image: '/images/vehicle_swift_dzire.png',
        features: ['Fuel efficient', 'Compact', 'AC', 'City friendly'],
    },
    {
        id: '2x3-nonac',
        name: 'Tempo Traveller',
        type: 'Non AC',
        category: '2x3',
        seatingCapacity: 12,
        pricePerKm: 24,
        image: '/images/vehicle_tempo_traveller.png',
        features: ['12 seater', 'Group travel', 'Ample luggage space'],
    },
];

export const services: Service[] = [
    {
        id: 'local',
        name: 'Local Trips',
        description: 'Explore your city with our reliable local cab service',
        icon: 'MapPin',
        type: 'Local',
        image: '/images/service_local_trip.png',
    },
    {
        id: 'intercity',
        name: 'Intercity Travel',
        description: 'Travel between cities in comfort and style',
        icon: 'Route',
        type: 'Intercity',
        image: '/images/service_intercity.png',
    },
    {
        id: 'city-tour',
        name: 'City Tours',
        description: 'Guided city tours with experienced drivers',
        icon: 'Building2',
        type: 'City Tour',
        image: '/images/service_city_tour.png',
    },
    {
        id: 'site-seeing',
        name: 'Site Seeing',
        description: 'Visit popular tourist attractions and landmarks',
        icon: 'Camera',
        type: 'Site Seeing',
        image: '/images/destination_munnar.png',
    },
    {
        id: 'airport',
        name: 'Airport Transfer',
        description: 'Timely and reliable airport pickup and drop',
        icon: 'Plane',
        type: 'Airport',
        image: '/images/service_airport_transfer.png',
    },
    {
        id: 'round-trip',
        name: 'Round Trip',
        description: 'Book for complete round trip journeys with better rates',
        icon: 'RotateCcw',
        type: 'Round Trip',
        image: '/images/destination_alleppey.png',
    },
];

export const categories: Category[] = [
    {
        id: 'car-rental',
        name: 'Car Rental with Driver',
        description: 'Hire a car with experienced driver for any occasion',
        icon: 'Car',
        count: 15,
        image: '/images/vehicle_innova.png',
    },
    {
        id: 'tour-operators',
        name: 'Tour Operators',
        description: 'Professional tour operators for Kerala and beyond',
        icon: 'Users',
        count: 8,
        image: '/images/service_local_trip.png',
    },
    {
        id: 'tour-packages',
        name: 'Tour Packages',
        description: 'Curated tour packages for all destinations',
        icon: 'Package',
        count: 49,
        image: '/images/destination_munnar.png',
    },
    {
        id: 'holiday-packages',
        name: 'Holiday Packages',
        description: 'Special holiday packages for festivals and vacations',
        icon: 'Palmtree',
        count: 12,
        image: '/images/destination_alleppey.png',
    },
];

export const reviews: Review[] = [
    // International Reviews - Malaysia
    {
        id: '1',
        userName: 'Ahmad bin Hassan',
        location: 'Kuala Lumpur, Malaysia',
        rating: 5,
        comment: 'Absolutely fantastic experience! We booked a 7-day Kerala tour and everything was perfectly organized. The driver spoke good English and knew all the best spots. My family loved the backwater houseboat experience - so peaceful and unique. Highly recommend Golden Globe Tours for anyone visiting from Malaysia!',
        date: '2025-12-20',
        helpful: 42,
        country: 'Malaysia',
    },
    {
        id: '2',
        userName: 'Siti Nurhaliza',
        location: 'Penang, Malaysia',
        rating: 5,
        comment: 'We flew from Penang to Kochi for our honeymoon and booked the Kerala Honeymoon package. The houseboat experience was magical - candlelit dinner on the deck was so romantic! Our driver was very professional and gave us privacy when needed. Worth every penny!',
        date: '2025-12-15',
        helpful: 38,
        country: 'Malaysia',
    },
    // Singapore
    {
        id: '3',
        userName: 'Tan Wei Ming',
        location: 'Singapore',
        rating: 5,
        comment: 'As a Singaporean, I\'ve traveled extensively but Kerala was special. Golden Globe Tours made it seamless - airport pickup was on time, vehicles were clean and well-maintained. The Munnar tea plantations and Thekkady wildlife sanctuary were highlights. Driver Raju was knowledgeable and shared interesting stories about Kerala culture.',
        date: '2025-12-12',
        helpful: 51,
        country: 'Singapore',
    },
    {
        id: '4',
        userName: 'Priya Rajendran',
        location: 'Singapore',
        rating: 5,
        comment: 'Excellent service from start to finish! Booked the Complete Kerala Tour package. Everything was well planned - accommodations, transportation, sightseeing. The team was responsive on WhatsApp throughout. Athirapally waterfalls and Kovalam beach were stunning. Will definitely use them again!',
        date: '2025-12-08',
        helpful: 45,
        country: 'Singapore',
    },
    // Dubai & UAE
    {
        id: '5',
        userName: 'Mohammed Al Rashid',
        location: 'Dubai, UAE',
        rating: 5,
        comment: 'Coming from Dubai, I\'ve experienced luxury travel services worldwide. Golden Globe Tours impressed me with their professionalism and attention to detail. The Toyota Innova was spotless and comfortable. Our driver was punctual and courteous. Kerala\'s natural beauty combined with excellent service made this trip unforgettable.',
        date: '2025-12-05',
        helpful: 47,
        country: 'UAE',
    },
    {
        id: '6',
        userName: 'Fatima Al Zarooni',
        location: 'Abu Dhabi, UAE',
        rating: 5,
        comment: 'Wonderful family vacation! We\'re a family of 6 from Abu Dhabi and needed reliable transportation. The Tempo Traveller was perfect - spacious and air-conditioned. Golden Globe arranged everything beautifully - from Kerala backwaters to hill stations. Our children loved the elephant ride in Thekkady!',
        date: '2025-12-01',
        helpful: 40,
        country: 'UAE',
    },
    {
        id: '7',
        userName: 'Khalid Al Mansoori',
        location: 'Doha, Qatar',
        rating: 5,
        comment: 'Best tour operator in Kerala! Flew from Doha to Kochi for a week-long trip. The value for money is incredible compared to tours in the Gulf. Driver picked us up from Cochin International Airport right on time. Visited Munnar, Thekkady, Alleppey, and Kovalam - each place was beautiful. Highly recommend!',
        date: '2025-11-28',
        helpful: 36,
        country: 'Qatar',
    },
    // Canada
    {
        id: '8',
        userName: 'Sarah Mitchell',
        location: 'Toronto, Canada',
        rating: 5,
        comment: 'Came all the way from Toronto and this was the highlight of our India trip! Golden Globe Tours was recommended by a friend. The booking process was smooth, communication was excellent. Our driver spoke perfect English and was incredibly knowledgeable about Kerala\'s history and culture. The Wayanad wildlife experience was amazing!',
        date: '2025-11-25',
        helpful: 54,
        country: 'Canada',
    },
    {
        id: '9',
        userName: 'Rajesh Sharma',
        location: 'Vancouver, Canada',
        rating: 5,
        comment: 'As a Keralite living in Vancouver, I wanted to show my Canadian wife authentic Kerala. Golden Globe Tours delivered perfectly! Professional service, comfortable vehicles, great accommodations. My wife fell in love with the houseboat experience and Munnar\'s tea gardens. Thank you for making our trip special!',
        date: '2025-11-20',
        helpful: 48,
        country: 'Canada',
    },
    // South Africa
    {
        id: '10',
        userName: 'David van der Merwe',
        location: 'Cape Town, South Africa',
        rating: 5,
        comment: 'Exceptional service from South Africa! We booked the 7-day Kerala package and it exceeded all expectations. The driver was professional, the itinerary was well-planned with perfect timing. Kerala\'s backwaters remind me of our Knysna lagoons but with unique Indian charm. Highly recommended for South African travelers!',
        date: '2025-11-18',
        helpful: 43,
        country: 'South Africa',
    },
    {
        id: '11',
        userName: 'Nalini Padayachee',
        location: 'Durban, South Africa',
        rating: 5,
        comment: 'Fantastic experience! Visiting Kerala from Durban was on my bucket list. Golden Globe made everything easy - from airport pickup to dropping us back. The spice plantations in Thekkady reminded me of home. Driver was patient with our questions and helped us discover authentic Kerala cuisine. Worth the long flight!',
        date: '2025-11-15',
        helpful: 39,
        country: 'South Africa',
    },
    // Indian Reviews (Local & Domestic)
    {
        id: '12',
        userName: 'Rahul Menon',
        location: 'Ottapalam, Kerala',
        rating: 5,
        comment: 'Local resident here - used Golden Globe for my parents\' pilgrimage trip to Sabarimala and Guruvayur. Excellent service! Driver was respectful and knew all the routes perfectly. Very affordable pricing for locals. Will definitely use again for family trips.',
        date: '2025-11-12',
        helpful: 28,
        country: 'India',
    },
    {
        id: '13',
        userName: 'Priya Nair',
        location: 'Palakkad, Kerala',
        rating: 5,
        comment: 'Booked a Munnar trip package for my anniversary. Everything was perfectly arranged - the homestay was beautiful with amazing views. Our driver Raju was professional and gave us great recommendations for local restaurants. The rose garden and tea museum were wonderful!',
        date: '2025-11-10',
        helpful: 32,
        country: 'India',
    },
    {
        id: '14',
        userName: 'Suresh Kumar',
        location: 'Delhi, India',
        rating: 5,
        comment: 'Came from Delhi to explore God\'s Own Country. Golden Globe Tours made it hassle-free! The complete Kerala package covered everything - hills, beaches, backwaters, wildlife. Driver was knowledgeable and shared interesting facts about each location. The houseboat stay in Alleppey was the highlight!',
        date: '2025-11-08',
        helpful: 35,
        country: 'India',
    },
    {
        id: '15',
        userName: 'Anjali Reddy',
        location: 'Bangalore, India',
        rating: 5,
        comment: 'Weekend getaway from Bangalore to Wayanad was perfectly executed! Clean vehicle, professional driver, and great timing. The drive through Western Ghats was scenic. Visited Edakkal Caves and Soochipara Falls - absolutely beautiful. Reasonable pricing too!',
        date: '2025-11-05',
        helpful: 29,
        country: 'India',
    },
    {
        id: '16',
        userName: 'Lakshmi Krishnan',
        location: 'Thrissur, Kerala',
        rating: 5,
        comment: 'Organized our family reunion trip for 15 people from Thrissur. Golden Globe arranged multiple vehicles and coordinated everything perfectly. Visited Athirappilly waterfalls and Munnar. All drivers were synchronized and professional. Thank you for making our family trip memorable!',
        date: '2025-11-02',
        helpful: 41,
        country: 'India',
    },
    {
        id: '17',
        userName: 'Arun Kumar',
        location: 'Kochi, Kerala',
        rating: 5,
        comment: 'Used their airport transfer service multiple times. Always punctual, clean vehicles, and professional drivers. They track flight timings and adjust pickup accordingly. Very reliable for business travelers. Highly recommend!',
        date: '2025-10-30',
        helpful: 25,
        country: 'India',
    },
    {
        id: '18',
        userName: 'Deepa Iyer',
        location: 'Chennai, India',
        rating: 5,
        comment: 'Chennai to Kerala road trip was amazing! Covered Rameshwaram and then Kerala backwaters. Golden Globe handled the Kerala portion beautifully. Driver was experienced with overnight trips. The houseboat in Kumarakom was serene and peaceful. Great value for money!',
        date: '2025-10-28',
        helpful: 33,
        country: 'India',
    },
    {
        id: '19',
        userName: 'Mohammed Ashraf',
        location: 'Malappuram, Kerala',
        rating: 5,
        comment: 'Best taxi service in Kerala! Used them for pilgrimage trips and family functions. Always reliable, reasonable prices, and well-maintained vehicles. The drivers are respectful and know local areas well. Keep up the good work!',
        date: '2025-10-25',
        helpful: 30,
        country: 'India',
    },
    {
        id: '20',
        userName: 'Sreeja Mohan',
        location: 'Trivandrum, Kerala',
        rating: 5,
        comment: 'Local wedding transportation for 100+ guests was handled flawlessly! Multiple vehicles, all on time, professional drivers in traditional attire. Golden Globe made our special day stress-free. Highly recommend for events and weddings!',
        date: '2025-10-22',
        helpful: 37,
        country: 'India',
    },
    // More International Mix
    {
        id: '21',
        userName: 'Lee Jin-woo',
        location: 'Seoul, South Korea',
        rating: 5,
        comment: 'Amazing Kerala experience! Golden Globe driver met us at airport with name board. Very professional service. The Innova was comfortable for long drives. Kerala food and nature is beautiful. Driver helped us find halal and vegetarian restaurants. Excellent!',
        date: '2025-10-20',
        helpful: 34,
        country: 'South Korea',
    },
    {
        id: '22',
        userName: 'Emma Thompson',
        location: 'London, UK',
        rating: 5,
        comment: 'Brilliant service! Came from London for a  yoga retreat in Kerala. Golden Globe arranged all my transportations between ashram, beaches and sightseeing. Driver was patient and helpful. The backwaters were absolutely gorgeous. Kerala is a hidden gem!',
        date: '2025-10-18',
        helpful: 46,
        country: 'United Kingdom',
    },
    {
        id: '23',
        userName: 'Abdul Rahman',
        location: 'Sharjah, UAE',
        rating: 5,
        comment: 'Perfect family vacation from Sharjah! Kerala is much greener than UAE - kids loved it! Golden Globe organized everything professionally. The Kerala temples, beaches, and hill stations were all beautiful. Driver spoke Arabic which was helpful. Excellent service!',
        date: '2025-10-15',
        helpful: 38,
        country: 'UAE',
    },
    {
        id: '24',
        userName: 'Vijay Shankar',
        location: 'Coimbatore, India',
        rating: 5,
        comment: 'Regular customer from Coimbatore here! Used Golden Globe for 5+ trips now. Always consistent service - clean cars, professional drivers, fair pricing. Last trip covered Munnar and Thekkady. Driver helped us find hidden viewpoints not in guidebooks. Loyalty well-earned!',
        date: '2025-10-12',
        helpful: 31,
        country: 'India',
    },
];

export const photoCategories = [
    { id: 'drive-option', name: 'Drive Options' },
    { id: 'car-seating', name: 'Car Seating' },
    { id: 'capacity', name: 'Seating Capacity' },
    { id: 'rental-type', name: 'Rental Types' },
    { id: 'destinations', name: 'Destinations' },
];

export const stats = {
    totalPackages: 49,
    happyCustomers: 5000,
    yearsExperience: 10,
    vehiclesAvailable: 50,
    destinations: 15,
};
